apiVersion: v1
kind: PersistentVolume
metadata:
  name: giovana-images-k8
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/k8s/images
